// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Data;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250209055230_AddTaiKhoanIdToCuTri")]
    partial class AddTaiKhoanIdToCuTri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuTri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BoPhieu")
                        .HasColumnType("bit");

                    b.Property<int>("CuocBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("CuocBauCuID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PhienBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("PhienBauCuID");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("SDT");

                    b.Property<int>("SoLanGuiOtp")
                        .HasColumnType("int")
                        .HasColumnName("SoLanGuiOTP");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<bool>("XacMinh")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__CuTri__3214EC27CBD841C7");

                    b.HasIndex("CuocBauCuId");

                    b.HasIndex("PhienBauCuId");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex(new[] { "Email" }, "UQ__CuTri__A9D10534D6D5F218")
                        .IsUnique();

                    b.HasIndex(new[] { "Sdt" }, "UQ__CuTri__CA1930A5375CB211")
                        .IsUnique();

                    b.ToTable("CuTri", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.CauHinhHeThong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCauHinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__CauHinhH__3214EC2794D0BC2A");

                    b.ToTable("CauHinhHeThong", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.ChucNang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ChucNang__3214EC27E7B6E84B");

                    b.HasIndex(new[] { "TenChucNang" }, "UQ__ChucNang__CFD37AFA69DDD913")
                        .IsUnique();

                    b.ToTable("ChucNang", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.CuocBauCu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("TenCuocBauCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__CuocBauC__3214EC27927CACAC");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("CuocBauCu", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.LichSuHoatDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoatDong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__LichSuHo__3214EC27BB880488");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("LichSuHoatDong", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.PhienBauCu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuocBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("CuocBauCuID");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("TenPhienBauCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__PhienBau__3214EC279845F2B0");

                    b.HasIndex("CuocBauCuId");

                    b.ToTable("PhienBauCu", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.PhieuBau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuTriId")
                        .HasColumnType("int")
                        .HasColumnName("CuTriID");

                    b.Property<int>("CuocBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("CuocBauCuID");

                    b.Property<int?>("PhienBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("PhienBauCuID");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("UngCuVienId")
                        .HasColumnType("int")
                        .HasColumnName("UngCuVienID");

                    b.Property<int>("ViTriUngCuId")
                        .HasColumnType("int")
                        .HasColumnName("ViTriUngCuID");

                    b.HasKey("Id")
                        .HasName("PK__PhieuBau__3214EC27BE61F897");

                    b.HasIndex("CuTriId");

                    b.HasIndex("CuocBauCuId");

                    b.HasIndex("PhienBauCuId");

                    b.HasIndex("UngCuVienId");

                    b.HasIndex("ViTriUngCuId");

                    b.ToTable("PhieuBau", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("LanDangNhapCuoi")
                        .HasColumnType("date");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateOnly?>("NgayThamGia")
                        .HasColumnType("date");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__TaiKhoan__3214EC27D89FB40D");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__TaiKhoan__55F68FC0C79307E2")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.TaiKhoanVaiTroAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    b.HasKey("Id")
                        .HasName("PK__TaiKhoan__3214EC278D24B91C");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("TaiKhoanVaiTroAdmin", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.TaiKhoanVaiTroUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CuocBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("CuocBauCuID");

                    b.Property<int?>("PhienBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("PhienBauCuID");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    b.HasKey("Id")
                        .HasName("PK__TaiKhoan__3214EC2711CBAC23");

                    b.HasIndex("CuocBauCuId");

                    b.HasIndex("PhienBauCuId");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("TaiKhoanVaiTroUser", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__ThongBao__3214EC277ABA96BB");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.UngCuVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CuocBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("CuocBauCuID");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhienBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("PhienBauCuID");

                    b.Property<int>("ViTriUngCuId")
                        .HasColumnType("int")
                        .HasColumnName("ViTriUngCuID");

                    b.HasKey("Id")
                        .HasName("PK__UngCuVie__3214EC27864EE498");

                    b.HasIndex("CuocBauCuId");

                    b.HasIndex("PhienBauCuId");

                    b.HasIndex("ViTriUngCuId");

                    b.ToTable("UngCuVien", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.VKetQuaPhienBauCu", b =>
                {
                    b.Property<int?>("PhienBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("PhienBauCuID");

                    b.Property<int?>("SoPhieu")
                        .HasColumnType("int");

                    b.Property<int>("UngCuVienId")
                        .HasColumnType("int")
                        .HasColumnName("UngCuVienID");

                    b.ToTable((string)null);

                    b.ToView("vKetQuaPhienBauCu", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.VPhieuBau", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("SdtcuTri")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("SDTCuTri");

                    b.Property<string>("TenCuocBauCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhienBauCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenUngCuVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenViTriUngCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.ToTable((string)null);

                    b.ToView("vPhieuBau", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.VTrangThaiPbc", b =>
                {
                    b.Property<int>("CuocBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("CuocBauCuID");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("TenPhienBauCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.ToTable((string)null);

                    b.ToView("vTrangThai_PBC", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__VaiTro__3214EC27D51DCEC4");

                    b.HasIndex(new[] { "TenVaiTro" }, "UQ__VaiTro__1DA5581450B576A1")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.VaiTroChucNang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChucNangId")
                        .HasColumnType("int")
                        .HasColumnName("ChucNangID");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    b.HasKey("Id")
                        .HasName("PK__VaiTroCh__3214EC2722F02E55");

                    b.HasIndex("ChucNangId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("VaiTroChucNang", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.ViTriUngCu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuocBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("CuocBauCuID");

                    b.Property<int?>("PhienBauCuId")
                        .HasColumnType("int")
                        .HasColumnName("PhienBauCuID");

                    b.Property<int>("SoPhieuToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenViTriUngCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__ViTriUng__3214EC273EF067E8");

                    b.HasIndex("CuocBauCuId");

                    b.HasIndex("PhienBauCuId");

                    b.ToTable("ViTriUngCu", (string)null);
                });

            modelBuilder.Entity("WebApplication3.Models.VtrangThaiCbc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("TenCuocBauCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.ToTable((string)null);

                    b.ToView("VTrangThai_CBC", (string)null);
                });

            modelBuilder.Entity("CuTri", b =>
                {
                    b.HasOne("WebApplication3.Models.CuocBauCu", "CuocBauCu")
                        .WithMany("CuTris")
                        .HasForeignKey("CuocBauCuId")
                        .IsRequired()
                        .HasConstraintName("FK__CuTri__CuocBauCu__48CFD27E");

                    b.HasOne("WebApplication3.Models.PhienBauCu", "PhienBauCu")
                        .WithMany("CuTris")
                        .HasForeignKey("PhienBauCuId")
                        .HasConstraintName("FK__CuTri__PhienBauC__49C3F6B7");

                    b.HasOne("WebApplication3.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("CuocBauCu");

                    b.Navigation("PhienBauCu");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebApplication3.Models.CuocBauCu", b =>
                {
                    b.HasOne("WebApplication3.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("CuocBauCus")
                        .HasForeignKey("TaiKhoanId")
                        .HasConstraintName("FK_CuocBauCu_TaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebApplication3.Models.LichSuHoatDong", b =>
                {
                    b.HasOne("WebApplication3.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebApplication3.Models.PhienBauCu", b =>
                {
                    b.HasOne("WebApplication3.Models.CuocBauCu", "CuocBauCu")
                        .WithMany("PhienBauCus")
                        .HasForeignKey("CuocBauCuId")
                        .IsRequired()
                        .HasConstraintName("FK__PhienBauC__CuocB__398D8EEE");

                    b.Navigation("CuocBauCu");
                });

            modelBuilder.Entity("WebApplication3.Models.PhieuBau", b =>
                {
                    b.HasOne("CuTri", "CuTri")
                        .WithMany("PhieuBaus")
                        .HasForeignKey("CuTriId")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuBau__CuTriI__4D94879B");

                    b.HasOne("WebApplication3.Models.CuocBauCu", "CuocBauCu")
                        .WithMany("PhieuBaus")
                        .HasForeignKey("CuocBauCuId")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuBau__CuocBa__5070F446");

                    b.HasOne("WebApplication3.Models.PhienBauCu", "PhienBauCu")
                        .WithMany("PhieuBaus")
                        .HasForeignKey("PhienBauCuId")
                        .HasConstraintName("FK__PhieuBau__PhienB__4F7CD00D");

                    b.HasOne("WebApplication3.Models.UngCuVien", "UngCuVien")
                        .WithMany("PhieuBaus")
                        .HasForeignKey("UngCuVienId")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuBau__UngCuV__4CA06362");

                    b.HasOne("WebApplication3.Models.ViTriUngCu", "ViTriUngCu")
                        .WithMany("PhieuBaus")
                        .HasForeignKey("ViTriUngCuId")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuBau__ViTriU__4E88ABD4");

                    b.Navigation("CuTri");

                    b.Navigation("CuocBauCu");

                    b.Navigation("PhienBauCu");

                    b.Navigation("UngCuVien");

                    b.Navigation("ViTriUngCu");
                });

            modelBuilder.Entity("WebApplication3.Models.TaiKhoanVaiTroAdmin", b =>
                {
                    b.HasOne("WebApplication3.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoanVaiTroAdmins")
                        .HasForeignKey("VaiTroId")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoanV__VaiTr__68487DD7");

                    b.Navigation("TaiKhoan");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("WebApplication3.Models.TaiKhoanVaiTroUser", b =>
                {
                    b.HasOne("WebApplication3.Models.CuocBauCu", "CuocBauCu")
                        .WithMany("TaiKhoanVaiTroUsers")
                        .HasForeignKey("CuocBauCuId")
                        .HasConstraintName("FK__TaiKhoanV__CuocB__6383C8BA");

                    b.HasOne("WebApplication3.Models.PhienBauCu", "PhienBauCu")
                        .WithMany("TaiKhoanVaiTroUsers")
                        .HasForeignKey("PhienBauCuId")
                        .HasConstraintName("FK__TaiKhoanV__Phien__6477ECF3");

                    b.HasOne("WebApplication3.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoanVaiTroUsers")
                        .HasForeignKey("VaiTroId")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoanV__VaiTr__628FA481");

                    b.Navigation("CuocBauCu");

                    b.Navigation("PhienBauCu");

                    b.Navigation("TaiKhoan");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("WebApplication3.Models.ThongBao", b =>
                {
                    b.HasOne("WebApplication3.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebApplication3.Models.UngCuVien", b =>
                {
                    b.HasOne("WebApplication3.Models.CuocBauCu", "CuocBauCu")
                        .WithMany("UngCuViens")
                        .HasForeignKey("CuocBauCuId")
                        .IsRequired()
                        .HasConstraintName("FK__UngCuVien__CuocB__4316F928");

                    b.HasOne("WebApplication3.Models.PhienBauCu", "PhienBauCu")
                        .WithMany("UngCuViens")
                        .HasForeignKey("PhienBauCuId")
                        .HasConstraintName("FK__UngCuVien__Phien__440B1D61");

                    b.HasOne("WebApplication3.Models.ViTriUngCu", "ViTriUngCu")
                        .WithMany("UngCuViens")
                        .HasForeignKey("ViTriUngCuId")
                        .IsRequired()
                        .HasConstraintName("FK__UngCuVien__ViTri__4222D4EF");

                    b.Navigation("CuocBauCu");

                    b.Navigation("PhienBauCu");

                    b.Navigation("ViTriUngCu");
                });

            modelBuilder.Entity("WebApplication3.Models.VaiTroChucNang", b =>
                {
                    b.HasOne("WebApplication3.Models.ChucNang", "ChucNang")
                        .WithMany("VaiTroChucNangs")
                        .HasForeignKey("ChucNangId")
                        .IsRequired()
                        .HasConstraintName("FK__VaiTroChu__ChucN__5EBF139D");

                    b.HasOne("WebApplication3.Models.VaiTro", "VaiTro")
                        .WithMany("VaiTroChucNangs")
                        .HasForeignKey("VaiTroId")
                        .IsRequired()
                        .HasConstraintName("FK__VaiTroChu__VaiTr__5DCAEF64");

                    b.Navigation("ChucNang");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("WebApplication3.Models.ViTriUngCu", b =>
                {
                    b.HasOne("WebApplication3.Models.CuocBauCu", "CuocBauCu")
                        .WithMany("ViTriUngCus")
                        .HasForeignKey("CuocBauCuId")
                        .IsRequired()
                        .HasConstraintName("FK__ViTriUngC__CuocB__3F466844");

                    b.HasOne("WebApplication3.Models.PhienBauCu", "PhienBauCu")
                        .WithMany("ViTriUngCus")
                        .HasForeignKey("PhienBauCuId")
                        .HasConstraintName("FK__ViTriUngC__Phien__3E52440B");

                    b.Navigation("CuocBauCu");

                    b.Navigation("PhienBauCu");
                });

            modelBuilder.Entity("CuTri", b =>
                {
                    b.Navigation("PhieuBaus");
                });

            modelBuilder.Entity("WebApplication3.Models.ChucNang", b =>
                {
                    b.Navigation("VaiTroChucNangs");
                });

            modelBuilder.Entity("WebApplication3.Models.CuocBauCu", b =>
                {
                    b.Navigation("CuTris");

                    b.Navigation("PhienBauCus");

                    b.Navigation("PhieuBaus");

                    b.Navigation("TaiKhoanVaiTroUsers");

                    b.Navigation("UngCuViens");

                    b.Navigation("ViTriUngCus");
                });

            modelBuilder.Entity("WebApplication3.Models.PhienBauCu", b =>
                {
                    b.Navigation("CuTris");

                    b.Navigation("PhieuBaus");

                    b.Navigation("TaiKhoanVaiTroUsers");

                    b.Navigation("UngCuViens");

                    b.Navigation("ViTriUngCus");
                });

            modelBuilder.Entity("WebApplication3.Models.TaiKhoan", b =>
                {
                    b.Navigation("CuocBauCus");
                });

            modelBuilder.Entity("WebApplication3.Models.UngCuVien", b =>
                {
                    b.Navigation("PhieuBaus");
                });

            modelBuilder.Entity("WebApplication3.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoanVaiTroAdmins");

                    b.Navigation("TaiKhoanVaiTroUsers");

                    b.Navigation("VaiTroChucNangs");
                });

            modelBuilder.Entity("WebApplication3.Models.ViTriUngCu", b =>
                {
                    b.Navigation("PhieuBaus");

                    b.Navigation("UngCuViens");
                });
#pragma warning restore 612, 618
        }
    }
}
