module.exports = [
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
  },
  {
    type: "function",
    name: "currentPhase",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "enum ElectionV1.Phase" }],
  },
  {
    type: "function",
    name: "commitStart",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
  },
  {
    type: "function",
    name: "commitEnd",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
  },
  {
    type: "function",
    name: "revealEnd",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
  },
  {
    type: "function",
    name: "finalized",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
  },
  {
    type: "function",
    name: "totalCommits",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "totalReveals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "getCandidateIds",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32[]", internalType: "bytes32[]" }],
  },
  {
    type: "function",
    name: "getResults",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "candidateIds", type: "bytes32[]", internalType: "bytes32[]" },
      { name: "counts", type: "uint256[]", internalType: "uint256[]" },
    ],
  },
];
